- app/mock-data/mock-apis.ts
- app/mock-data/mock-quote-options.ts
- app/package-lock.json
- app/src/App.tsx
- app/src/constants/types.ts
- app/src/context/swap.context.tsx
- app/src/main.tsx
We should be able to replace `getSwapQuotes` with `swapService` methods now, which is compatible with `SwapService` mojo interface in brave-core.
> feat: add swapService to SwapProvider

- app/mock-data/mock-apis.ts
- app/src/context/swap.context.tsx
This is done to match the mojo service, so we can directly use it in the `swapService` prop.
> feat(swap): add isSwapSupported to SwapService to match brave-core

- app/src/components/swap/to-section.tsx
- app/src/hooks/useJupiter.ts
- app/src/hooks/useSwap.ts
- app/src/hooks/useZeroEx.ts
- app/src/views/swap.tsx
Once a quote has been fetched, subsequent calls to `.refresh()` should not make the previous quote details disappear while another call is in progress.
Also added an effect to invoke `.refresh()` periodically.
⚠️ Note how the To box increases in height while displaying the loader. I was unable to do the fix in CSS.
https://user-images.githubusercontent.com/3684187/191546000-c917553f-f94f-4841-9b94-c226e539371b.mov
> feat(swap): refresh quotes periodically and adjust loader accordingly

- app/src/components/swap/account-selector.tsx
- app/src/components/swap/swap-and-send.tsx
Fixes a bug where the `Select Account` selector would not hide if you clicked on the `Send to Address` radio button.
Also now resets the `Selected Account` to `undefined` if the user clicks on the `Send to Address` radio button.
Resolves <https://github.com/brave/brave-browser/issues/25538>
Before:
https://user-images.githubusercontent.com/40611140/191611268-6ed556a6-659a-46ee-94d7-812af04afac3.mov
After:
https://user-images.githubusercontent.com/40611140/191611303-5d496b76-5e3b-40f7-8dae-30bf4dbd0750.mov
> fix(swap): Select Account Selector not Hiding

- app/mock-data/mock-apis.ts
- app/mock-data/mock-networks.ts
- app/src/App.tsx
- app/src/constants/locale.ts
- app/src/constants/magics.ts
- app/src/constants/types.ts
- app/src/context/swap.context.tsx
- app/src/hooks/useJupiter.ts
- app/src/hooks/useSwap.ts
- app/src/hooks/useZeroEx.ts
- app/src/main.tsx
- app/src/utils/hex-utils.ts
- app/src/views/swap.tsx
No visual changes. The idea is to have an `ethWalletAdapter` and a `solWalletAdapter` containing chain-specific methods, particularly for creating transactions.
Special care was taken to avoid the `useEffect` mess in the legacy implementation of `useSwap` hook.
> feat: implement wallet adapters and trigger exchange() on submit

- interface/package-lock.json
- interface/package.json
- interface/src/App.tsx
- interface/src/components/buttons/connect-wallet-button.tsx
- interface/src/components/buttons/select-quote-option-button.tsx
- interface/src/components/swap/account-selector.tsx
- interface/src/components/swap/header.tsx
- interface/src/components/swap/network-selector.tsx
- interface/src/components/swap/quote-info.tsx
- interface/src/components/swap/search-with-network-selector.tsx
- interface/src/components/swap/select-token-modal.tsx
- interface/src/components/swap/settings/gas-preset-button.tsx
- interface/src/components/swap/settings/swap-settings-modal.tsx
- interface/src/components/swap/swap-container.tsx
- interface/src/context/swap.context.tsx
- interface/src/hooks/useJupiter.ts
- interface/src/hooks/useNetworkFees.ts
- interface/src/hooks/useSwap.ts
- interface/src/hooks/useZeroEx.ts
- interface/src/state/types.ts
- interface/src/state/wallet.tsx
- interface/src/views/swap.tsx
- sites/mock/mock-data/mock-apis.ts
- sites/mock/package-lock.json
- sites/mock/src/main.tsx
Using React props for stuff like `selectedAccount`, `selectedNetwork`, etc, allows us to avoid maintaining a state and update it whenever the caller (brave-core in our case) has a change.
Also added switcher methods for network and account.
> chore: refactor interface to use props + add network/account switcher

- interface/package-lock.json
- interface/package.json
- interface/src/hooks/useZeroEx.ts
- sites/mock/package-lock.json
No demo available, since `exchange()` creates an actual transaction.
> Fix broken exchange() implementation for 0x swaps

- interface/src/index.css
- sites/mock/src/index.css
- sites/mock/src/main.tsx
Compiled `style.css` no longer contains the HTTP url of the font, which would otherwise crash brave-core
> Externalize font to prevent brave-core from crashing

- interface/src/hooks/useNativeAsset.ts
- interface/src/hooks/useSwap.ts
- interface/src/state/wallet.tsx
For some reason, the network passed from `brave-core` keeps triggering a re-render even if the fields are static. Introduced a new hook called `useNativeAsset` to tackle this.
> fix: prevent unnecessary rerendering for the same network object

- interface/package-lock.json
- interface/package.json
- interface/src/components/swap/account-modal/account-modal.tsx
- interface/src/components/swap/account-selector.tsx
- interface/src/components/swap/header.tsx
- interface/src/components/swap/network-selector.tsx
- interface/src/components/swap/search-with-network-selector.tsx
- interface/src/components/swap/select-token-modal.tsx
- interface/src/components/swap/swap-container.tsx
- interface/src/constants/types.ts
- interface/src/hooks/useSwap.ts
- interface/src/state/wallet.tsx
- interface/src/views/swap.tsx
- sites/mock/mock-data/mock-tokens.ts
- sites/mock/package-lock.json
`walletAccounts` and `assetsList` now contain information for all networks.
On changing the network or account, we filter the above lists on the fly and use them for refreshing the blockchain state. This ensures consistency. In the event that the account is inconsistent with the network, we again `walletAccounts` to get the first account with the right `coin` value.
> feat: optimise fetching of blockchain state on network/account switch

- interface/package-lock.json
- interface/package.json
- interface/src/hooks/useSwap.ts
- interface/src/utils/assets.ts
- sites/mock/package-lock.json
Previously, when you changed the network, you'd see the balances of the old network for a few seconds until the fresh balances were updated. This PR prevents displaying such stale information in the frontend.
> fix: partition balances by coin type and chainId

- interface/package-lock.json
- interface/package.json
- interface/src/components/swap/account-modal/account-modal.tsx
- interface/src/components/swap/header.tsx
- interface/src/components/swap/search-with-network-selector.tsx
- interface/src/components/swap/select-token-modal.tsx
- interface/src/components/swap/swap-container.tsx
- interface/src/components/swap/virtualized-tokens-list.tsx
- interface/src/hooks/useSwap.ts
- interface/src/views/swap.tsx
- sites/mock/package-lock.json
Balance updates just got a makeover! Here's how it works:
- We maintain a balance registry which is gradually populated. Think of it as a cache. Until the cached balance is populated for a particular token, the balance is considered zero.
- On changing the From asset, we fetch the live balance for the new token and update the cache.
- On first load of the swap app, we fetch balances for all available tokens, and populate the cache. This is done in a throttled manner so as to not overwhelm the event loop. We currently use 10 concurrent workers, and split the tokens list in chunks of 10 so we don't have to wait for all balances to be available before starting to see them in the UI.
https://user-images.githubusercontent.com/3684187/199628575-1ba223c6-8b80-4f45-9b4e-4c3988ee1407.mov
> feat: throttle async requests to improve performance

- .github/workflows/audit.yml
The third-party npm action did not support `working-directory` key.
> fix: do not use third-party npm audit action

- interface/package-lock.json
- interface/package.json
- sites/mock/package-lock.json
Apparently, leo now requires `svelte2tsx` for some pre-install scripts. I added it to the `devDependencies`.
> chore: use leo package from brave org

- interface/package-lock.json
- interface/package.json
- sites/mock/package-lock.json
Couldn't install swap-interface in brave-core without having this as a dev dependency, as leo depends on it for the build.
> chore: add postcss-js to dev-dependencies

- interface/src/hooks/useDebouncedCallback.ts
- interface/src/hooks/useSwap.ts
- interface/src/hooks/useZeroEx.ts
- interface/src/vite-env.d.ts
This PR introduces two main features:
1. Inputs are debounced to prevent triggering refresh of quotes too often.
2. Fetching of quotes can be cancelled in-flight due to a reset.
1. If a quote is being fetched, clearing the either of the From or To inputs should cancel the fetch.
2. New quotes are only fetched after 700ms of the last update to the From or To amounts.
- Clearing From amount, using Ctrl+A following by Delete, should reset the quotes.
- Clearing To amount, using Ctrl+A following by Delete, should reset the quotes.
- Enter a very long amount in the From field, such as `1.23456789`. Long press the Delete key until all entire amount is cleared. This should trigger a reset and not result in a zombie quote (a quote that exists without either From or To amounts).
- Changing the …
> feat: add input debouncing, in-flight cancellation, and reset improvements

- interface/package-lock.json
- interface/package.json
- interface/src/hooks/useSwap.ts
- sites/mock/package-lock.json
Added the missing condition for Solana, to disable the CTA button in case of errors.
|Issue|https://github.com/brave/brave-browser/issues/28623|
-|-
> fix: disable CTA button for Solana validation errors

- interface/package-lock.json
- interface/package.json
- interface/src/hooks/useDebouncedCallback.ts
- interface/src/hooks/useSwap.ts
- sites/mock/package-lock.json
Use debounced version of `refreshBlockchainState()` and `refreshSpotPrices()` on first load. This prevents Swap from calling these functions multiple times (due to changing hook dependencies) on initialisation.
The code works with a 0ms debounce, but I don't know why. I tested this PR with `console.log` statements.
|Issue|https://github.com/brave/brave-browser/issues/28635|
-|-
> fix: prevent duplicate blockchain state refresh on first load

- interface/package-lock.json
- interface/package.json
- interface/src/App.tsx
- interface/src/context/swap.context.tsx
- interface/src/hooks/useSwap.ts
- interface/src/utils/assets.ts
- sites/mock/mock-data/mock-apis.ts
- sites/mock/package-lock.json
- sites/mock/src/main.tsx
|Issue|https://github.com/brave/brave-browser/issues/28634|
-|-
⚠️ This PR is compatible only with brave-core 1.50.x. The MAJOR version has been bumped due to change in interface.
|   |Before|After|
|--|-------|----|
|**Ethereum**|45s|4s|
|**Polygon**|13s|4s|
|**Optimism**|9s|4s|
|**BSC**|12s|2s|
|   |Before|After|
|--|-------|----|
|**Ethereum**|20s|2s|
|**Polygon**|6s|2s|
|**Optimism**|4s|2s|
|**BSC**|4s|1s|
> feat: integrate token balances scanner

- interface/src/constants/types.ts
- interface/src/hooks/useJupiter.ts
- interface/src/hooks/useNativeAsset.ts
- interface/src/hooks/useSwap.ts
- interface/src/hooks/useZeroEx.ts
- interface/src/views/swap.tsx
The Jupiter Swap UI is not ready for `swapMode=ExactOut`. This PR hardcodes it to `ExactIn` + does some code improvements and cleanups.
Also passing a `sendOption` of `maxRetries=2` for greater reliability of transaction broadcasts.
> chore: hardcode swapMode to ExactIn + cleanups

- interface/package-lock.json
- interface/package.json
- interface/src/hooks/useJupiter.ts
Since we do not support `ExactOut` swap mode, might as well enable minimum received amount.
> Enable minimum received amount after slippage for Jupiter

- interface/package-lock.json
- interface/package.json
- interface/src/hooks/useJupiter.ts
- sites/mock/package-lock.json
To be able to cancel in-flight requests to Jupiter API.
> feat: add AbortController to refresh() in useJupiter hook

- interface/package-lock.json
- interface/package.json
- interface/src/constants/types.ts
- interface/src/hooks/useJupiter.ts
- interface/src/hooks/useSwap.ts
- interface/src/hooks/useZeroEx.ts
- sites/mock/package-lock.json
`slippageTolerance` in `useSwap.ts` now describes the UI-level concept (i.e., value entered by the user) and the hooks specific to the swap provider make sure this value is transformed into appropriate format.
**For example:**
If user selects `0.5` in the UI as slippage tolerance, then:
- `slippageTolerance` is `0.5`
- `slippageBps` for Jupiter is `50`.
- `slippagePercentage` for 0x is `0.005`.
> fix: improve code clarity + prevent decimal slippageBps value
