brave/swap

app/src/App.tsx, app/src/components/swap/from-section.tsx, app/src/components/swap/select-token-modal.tsx
Handle the value change via the existing onInputChange prop
=> fix: remove onClickPresetAmount prop

app/mock-data/mock-accounts.ts, app/mock-data/mock-api-data.ts, app/mock-data/mock-apis.ts, app/mock-data/mock-spot-prices.ts, app/mock-data/mock-tokens.ts, app/src/App.tsx, app/src/components/buttons/select-quote-option-button.tsx, app/src/components/buttons/select-token-or-network-button.tsx, app/src/components/swap/from-section.tsx, app/src/components/swap/quote-options.tsx, app/src/components/swap/search-with-network-selector.tsx, app/src/components/swap/select-token-modal.tsx, app/src/components/swap/to-section.tsx, app/src/constants/locale.ts, app/src/constants/magics.ts, app/src/constants/types.ts, app/src/context/swap.context.tsx, app/src/main.tsx, app/src/state/types.ts, app/src/state/wallet.tsx, app/src/views/swap.tsx
Setup `SwapContextProvider` to take in the following methods
- getLocale
- getBalance
- getERC20TokenBalance
- getAllTokens
- getSelectedAccount
- getSelectedNetwork
- getTokenPrice
- getSwapQuotes
Setup `WalletStateProvider` to be used through out the project
Resolves <https://github.com/brave/brave-browser/issues/24526>
=> feat(swap): Setup Context and State Management

app/src/hooks/useSwap.ts, app/src/views/swap.tsx
Setup `useSwap` hook
Resolves <https://github.com/brave/brave-browser/issues/24756>
=> feat(swap): Setup useSwap Hook

app/mock-data/mock-tokens.ts, app/src/components/buttons/connect-wallet-button.tsx, app/src/components/swap/quote-info.tsx, app/src/constants/locale.ts, app/src/state/types.ts, app/src/state/wallet.tsx, app/src/utils/api-utils.ts, app/src/views/swap.tsx
Built out `CoinGecko Price Comparison` components
Resolves <https://github.com/brave/brave-browser/issues/24976>
https://user-images.githubusercontent.com/40611140/188018401-c0c60bea-3493-428a-88ef-4c1b1b8509ab.mov
=> feat(swap): Built out CoinGecko Price Comparison

app/src/components/swap/swap-container.tsx
Fixes the `Network Selector` zIndex
Resolves <https://github.com/brave/brave-browser/issues/25482>
Before:
https://user-images.githubusercontent.com/40611140/191064651-6cb7c1ed-3934-4314-a9dc-baa3ec40c572.mov
After:
https://user-images.githubusercontent.com/40611140/191064672-49fc13ed-5cb7-4b24-b585-9769cb8ca814.mov
=> fix(swap): Network Selector zIndex

app/src/views/swap.tsx
Resets the `Slippage Tolerance` back to `0.5` if no value is defined after closing settings.
Resolves <https://github.com/brave/brave-browser/issues/25483>
Before:
https://user-images.githubusercontent.com/40611140/191068010-f00a6527-5e93-4bcd-8349-20fbf1a1e9db.mov
After:
https://user-images.githubusercontent.com/40611140/191068040-de8e64ee-0405-43d6-947b-9420d7cd3558.mov
=> fix(swap): Reset Slippage for Undefined Value

app/src/hooks/useSwap.ts
Fixes a bug where you couldn't flip `Undefined` tokens
Resolves <https://github.com/brave/brave-browser/issues/25486>
Before:
https://user-images.githubusercontent.com/40611140/191098974-fcbdba7c-c15e-4fa2-8705-79547d871c2b.mov
After:
https://user-images.githubusercontent.com/40611140/191099002-054bcc7b-cea9-418e-9a25-6434e33c21fc.mov
=> fix(swap): Allow Flipping Undefined Tokens

app/mock-data/mock-apis.ts, app/src/App.tsx, app/src/components/buttons/network-list-button.tsx, app/src/components/buttons/select-quote-option-button.tsx, app/src/components/buttons/select-token-or-network-button.tsx, app/src/components/swap/from-section.tsx, app/src/components/swap/header.tsx, app/src/components/swap/quote-info.tsx, app/src/context/swap.context.tsx, app/src/hooks/useNetworkFees.ts, app/src/hooks/useSwap.ts, app/src/main.tsx, app/src/state/types.ts, app/src/state/wallet.tsx
Adds support for `Local Fiat Currencies`
Resolves <https://github.com/brave/brave-browser/issues/25262>
https://user-images.githubusercontent.com/40611140/191556972-5efbb766-2753-493f-bcb5-7f4d50e7534e.mov
=> feat(swap): Support Local Fiat Currencies

app/src/components/boxes/swap-section-box.tsx, app/src/components/buttons/select-quote-option-button.tsx, app/src/components/shared.styles.ts, app/src/components/swap/to-section.tsx, app/src/views/swap.tsx
Fixes loading state styles for `To Section` box and Solana `Quote Options`
Resolves <https://github.com/brave/brave-browser/issues/25534>
Before:
https://user-images.githubusercontent.com/40611140/191598011-32c9894a-f1eb-4b22-8874-1c24ac1a7cf8.mov
After:
https://user-images.githubusercontent.com/40611140/191598043-0c1804f7-aab6-42a8-b54d-83dfd5c790e1.mov
=> fix(swap): Loading State Styles

app/src/components/boxes/swap-section-box.tsx, app/src/components/buttons/account-list-button.tsx, app/src/components/buttons/connect-wallet-button.tsx, app/src/components/buttons/flip-tokens-button.tsx, app/src/components/buttons/preset-button.tsx, app/src/components/buttons/select-quote-option-button.tsx, app/src/components/buttons/select-token-or-network-button.tsx, app/src/components/buttons/standard-button.tsx, app/src/components/buttons/theme-button.tsx, app/src/components/buttons/token-list-button.tsx, app/src/components/form-controls/standard-radio.tsx, app/src/components/form-controls/standard-switch.tsx, app/src/components/inputs/slippage-input.tsx, app/src/components/modals/standard-modal.tsx, app/src/components/swap/account-selector.tsx, app/src/components/swap/header.tsx, app/src/components/swap/network-selector.tsx, app/src/components/swap/quote-info.tsx, app/src/components/swap/settings/gas-preset-button.tsx, app/src/components/swap/settings/swap-settings-modal.tsx, app/src/index.css, app/src/theme/component-variables.css
Fixes a bug where `@media (prefers-color-scheme: dark)` does not respect local `data-theme` changes in the Swap UI.
To make it work, anywhere we need to use `prefers-color-scheme: dark`, we have to define the variable at the `root` level.
Resolves <https://github.com/brave/brave-browser/issues/25113>
Before:
https://user-images.githubusercontent.com/40611140/191853081-24440ca1-956e-4356-8ebb-1f5f774cd4ed.mov
After:
https://user-images.githubusercontent.com/40611140/191853113-5b82e539-d9e3-4c73-b928-7ac684e7a343.mov
=> fix(swap): Local Color Theme

app/src/components/swap/from-section.tsx, app/src/hooks/useSwap.ts
Fixes a bug where `From Balance` didn't updated after connecting.
Resolves <https://github.com/brave/brave-browser/issues/25700>
Before:
https://user-images.githubusercontent.com/40611140/193056550-3c600a99-9494-4704-beca-d6ebc0b83217.mov
After:
https://user-images.githubusercontent.com/40611140/193056655-f2b7d9c8-d1e3-4900-8e19-6046dd316f2b.mov
=> fix(swap): Update From Balance On Connect

app/src/components/buttons/connect-wallet-button.tsx, app/src/components/buttons/select-token-or-network-button.tsx, app/src/components/modals/standard-modal.tsx, app/src/components/shared.styles.ts, app/src/components/swap/header.tsx, app/src/components/swap/network-selector.tsx, app/src/components/swap/quote-info.tsx, app/src/components/swap/swap-container.tsx
Added `Media Queries` for a `Responsive` design
Resolves <https://github.com/brave/brave-browser/issues/25713>
https://user-images.githubusercontent.com/40611140/193130287-21ebaaf2-bb2e-477d-8c98-11647cfa621b.mov
=> fix(swap): Added Responsive Media Queries

app/src/components/modals/standard-modal.tsx, app/src/components/swap/header.tsx, app/src/components/swap/select-token-modal.tsx, app/src/components/swap/settings/swap-settings-modal.tsx, app/src/hooks/useOnClickOutside.ts, app/src/views/swap.tsx
Added a `useOnClickOutside` hook to allow dismissing `Modals` when a user clicks outside of the popup.
Resolves <https://github.com/brave/brave-browser/issues/25714>
Before:
https://user-images.githubusercontent.com/40611140/193603002-e9974ea3-5de3-4e5f-9056-87f23e359b0e.mov
After:
https://user-images.githubusercontent.com/40611140/193603045-c54d1d87-0278-4dee-9158-6e27f72c70cf.mov
=> fix(swap): Add Click Outside Hook

interface/package-lock.json, interface/package.json, sites/mock/package-lock.json, sites/mock/package.json, sites/mock/src/main.tsx
This is done in order to match the version we use in brave-core.
=> chore: downgrade react version to v16.14.0

interface/src/components/buttons/connect-wallet-button.tsx, interface/src/constants/locale.ts, sites/mock/src/constants/locale.ts
Added a `locale` string for `Connect Wallet`
Resolves <https://github.com/brave/brave-browser/issues/25916>
=> fix(swap): Connect Wallet Locale String

interface/src/components/buttons/select-token-or-network-button.tsx, interface/src/components/swap/header.tsx, interface/src/constants/locale.ts, interface/src/state/types.ts, interface/src/state/wallet.tsx, sites/mock/src/constants/locale.ts
Adds an indication if the users `Selected Network` is not supported by our swaps.
Resolves <https://github.com/brave/brave-browser/issues/25919>
=> feat(swap): Handle Unsupported Networks

interface/package-lock.json, interface/package.json, interface/src/components/buttons/token-list-button.tsx, interface/src/components/swap/from-section.tsx, interface/src/components/swap/select-token-modal.tsx, interface/src/hooks/useSwap.ts, interface/src/utils/assets.ts, interface/src/views/swap.tsx, sites/mock/mock-data/mock-api-data.ts, sites/mock/mock-data/mock-apis.ts, sites/mock/mock-data/mock-token-balances.ts, sites/mock/package-lock.json
No visual changes, but some fixes and cleanups around balances.
=> chore: refactor balances

interface/src/components/swap/quote-info.tsx, interface/src/constants/locale.ts, sites/mock/src/constants/locale.ts
Adds an `Advanced` section to the `Quote Info` view.
Resolves <https://github.com/brave/brave-browser/issues/25856>
https://user-images.githubusercontent.com/40611140/195421649-978397a2-106c-45c9-bdc6-e81999936560.mov
=> feat(swap): Advanced Quote Info Section

README.md, interface/package-lock.json, interface/package.json, interface/src/context/swap.context.tsx, interface/src/hooks/useJupiter.ts, interface/src/hooks/useNetworkFees.ts, interface/src/hooks/useOnClickOutside.ts, interface/src/hooks/useSwap.ts, interface/src/hooks/useZeroEx.ts, sites/mock/mock-data/mock-apis.ts, sites/mock/package-lock.json
See changes in `interface/src/context/swap.context.tsx` for an overview.
=> Simplify swap service interface

interface/src/components/buttons/network-list-button.tsx, interface/src/components/buttons/select-token-or-network-button.tsx, interface/src/components/buttons/token-list-button.tsx, interface/src/components/placeholders/create-icon-with-placeholder.tsx, interface/src/components/placeholders/index.ts, interface/src/components/swap/from-section.tsx, interface/src/components/swap/header.tsx, interface/src/components/swap/search-with-network-selector.tsx, interface/src/components/swap/to-section.tsx
Will now create a `Placeholder` icon for `Assets` or `Networks` with missing icons.
Resolves <https://github.com/brave/brave-browser/issues/26012>
https://user-images.githubusercontent.com/40611140/195734278-662d43f6-7fd3-4a7f-8e67-0b884541f9b7.mov
=> fix(swap): Add Icon Placeholders

interface/src/components/placeholders/create-icon-with-placeholder.tsx, interface/src/utils/string-utils.ts
Adds an additional check if an `icon` has a valid extension.
Resolves <https://github.com/brave/brave-browser/issues/26049>
=> fix(swap): Check is Valid Icon Extension

interface/src/components/swap/account-selector.tsx
- Allows dismissing the `popup` if clicked outside
- Allows the `Selector` box to grow for long names
- Allows the `popup` to grow for long names
Resolves <https://github.com/brave/brave-browser/issues/26053>
Before:
https://user-images.githubusercontent.com/40611140/195946773-ab5ca5c8-09cb-44de-9d0c-bba349ae2d68.mov
After:
https://user-images.githubusercontent.com/40611140/195946794-ec1b44d6-d4eb-464c-bca8-6ebae13cfa4f.mov
=> fix(swap): Send To Account Selector Bugs

interface/src/components/buttons/select-quote-option-button.tsx, interface/src/constants/locale.ts, sites/mock/src/constants/locale.ts
Added a `locale` string for `Best`
Resolves <https://github.com/brave/brave-browser/issues/26054>
=> fix(swap): Best Quote Option Locale String

interface/src/components/swap/account-modal/account-modal.tsx
Allows the `Account Modal` to dynamically grow in size for long account names.
Resolves <https://github.com/brave/brave-browser/issues/26133>
Before:
After:
=> fix(swap): Account Modal Sizing

interface/src/hooks/useSwap.ts
https://user-images.githubusercontent.com/3684187/196781244-e06a2afc-0d7d-425e-af67-fc8a1f7f595a.mov
=> fix: reset selected assets when network changes

interface/src/App.tsx, interface/src/components/buttons/connect-wallet-button.tsx, interface/src/components/buttons/token-list-button.tsx, interface/src/components/swap/account-modal/account-modal.tsx, interface/src/components/swap/from-section.tsx, interface/src/components/swap/header.tsx, interface/src/components/swap/select-token-modal.tsx, interface/src/context/swap.context.tsx, interface/src/hooks/useSwap.ts, interface/src/state/types.ts, interface/src/state/wallet.tsx, sites/mock/src/constants/locale.ts, sites/mock/src/main.tsx
https://user-images.githubusercontent.com/3684187/196943672-f1c96f26-2671-432e-a742-9505ac2a940e.mov
=> Add props for wallet connection/disconnection

interface/src/components/swap/header.tsx, interface/src/constants/magics.ts, interface/src/views/swap.tsx
Stores users selected theme in `LocalStorage`
Resolves <https://github.com/brave/brave-browser/issues/26369>
https://user-images.githubusercontent.com/40611140/198706242-24d9553e-252b-410c-ae66-897f50f5516b.mov
=> feat(swap): Add User Theme to Local Storage

interface/src/state/wallet.tsx
Not a silver bullet to our performance issues, but as soon as all the balances have been fetched, the UI is pretty fast now.
=> feat: optimise balance update action

interface/src/components/swap/swap-container.tsx
We now use `chainId's` for the background variables
Resolves <https://github.com/brave/brave-browser/issues/26445>
=> fix(swap): Use ChainId for Background Variables

interface/src/components/swap/select-token-modal.tsx
Fixes a bug where the `Hide Zero Balance` button would disappear randomly.
Resolves <https://github.com/brave/brave-browser/issues/26453>
Before:
https://user-images.githubusercontent.com/40611140/199337643-ba18d5e2-a9fc-4027-ad65-9907ae73da2e.mov
After:
https://user-images.githubusercontent.com/40611140/199337677-096a6d0a-36ee-4d2a-b473-11c50de221e6.mov
=> fix(swap): Hide Zero Balance Button Disappearing

interface/package-lock.json, interface/package.json, interface/src/components/swap/quote-info.tsx, sites/mock/package-lock.json
Fixes `Liquidity provider` text alignment
Resolves <https://github.com/brave/brave-browser/issues/26515>
Before:
After:
=> fix(swap): Liquidity Provider Text Alignment

interface/package-lock.json, interface/package.json, interface/src/components/swap/quote-info.tsx, interface/src/constants/types.ts, interface/src/hooks/useSwap.ts, sites/mock/package-lock.json
- Removed the `Advanced` option
- Hid `Minimum Received` for `Ethereum` networks
- Added a `key` to the `lp` map to fix `console` errors
Resolves <https://github.com/brave/brave-browser/issues/26551>
=> fix(swap): Update Quote Info UI

interface/package-lock.json, interface/package.json, interface/src/components/swap/settings/swap-settings-modal.tsx, interface/src/components/swap/settings/toggle-section.tsx, interface/src/hooks/useSwap.ts, interface/src/views/swap.tsx, sites/mock/package-lock.json
- `Direct Route` is now hidden for `Solana`
- `Exchanges` is now hidden for `Ethereum`
- `Optimized Fee` is completely removed.
Resolves <https://github.com/brave/brave-browser/issues/26586>
=> fix(swap): Update Swap Settings UI

interface/package-lock.json, interface/package.json, interface/src/components/swap/quote-info.tsx, interface/src/constants/types.ts, interface/src/hooks/useJupiter.ts, interface/src/hooks/useSwap.ts, interface/src/hooks/useZeroEx.ts, sites/mock/package-lock.json
https://user-images.githubusercontent.com/3684187/200717663-7abdccf0-0e6b-422d-86aa-fec8f4574af7.mov
=> Show network fee and miscellaneous other fixes

interface/package-lock.json, interface/package.json, interface/src/components/swap/quote-info.tsx, interface/src/constants/types.ts, interface/src/context/swap.context.tsx, interface/src/hooks/useJupiter.ts, interface/src/hooks/useSwap.ts, interface/src/hooks/useZeroEx.ts, sites/mock/mock-data/mock-apis.ts, sites/mock/mock-data/mock-tokens.ts, sites/mock/package-lock.json, sites/mock/src/constants/locale.ts, sites/mock/src/main.tsx
| Regular Swaps | Free swaps |
-|-
|<img src="https://user-images.githubusercontent.com/3684187/202517820-ab996931-b5f5-434a-887d-a31f268aaaa3.png">|<img src="https://user-images.githubusercontent.com/3684187/202517758-b658f906-12dc-4cb5-9f07-56bc01361686.png">|
=> Indicate Brave fee in quote info

interface/package-lock.json, interface/package.json, interface/src/constants/types.ts, interface/src/context/swap.context.tsx, interface/src/hooks/useJupiter.ts, interface/src/hooks/useSwap.ts, interface/src/hooks/useZeroEx.ts, sites/mock/mock-data/mock-apis.ts
Need for https://github.com/brave/brave-core/pull/16010
=> Swap error parsing at backend

interface/package-lock.json, interface/package.json, interface/src/components/swap/from-section.tsx, interface/src/utils/amount.ts, sites/mock/package-lock.json
Formates the `Half` preset amount to avoid `to many decimal places` error.
Resolves <https://github.com/brave/brave-browser/issues/27091>
=> fix(swap): Half Preset Amount Error

interface/src/components/swap/swap-container.tsx, sites/web/contexts/ethereum.tsx
- Fixes a bug when clicking `Connect`, there was a box that appeared behind the `RainbowKit` modal
- Fixes a bug when you switched between `local` page themes, `RainbowKit` did not update to the correct theme.
Resolves <https://github.com/brave/brave-browser/issues/27712>
https://user-images.githubusercontent.com/40611140/211421415-15c0ab21-0a6a-4760-b2ba-0e0da095c64e.mov
=> fix(swap): Rainbow Kit Styling Bugs

interface/package-lock.json, interface/package.json, interface/src/components/boxes/swap-section-box.tsx, interface/src/components/buttons/connect-wallet-button.tsx, interface/src/components/buttons/flip-tokens-button.tsx, interface/src/components/buttons/network-list-button.tsx, interface/src/components/buttons/select-token-or-network-button.tsx, interface/src/components/buttons/token-list-button.tsx, interface/src/components/form-controls/index.ts, interface/src/components/form-controls/theme-switch.tsx, interface/src/components/modals/standard-modal.tsx, interface/src/components/placeholders/create-icon-with-placeholder.tsx, interface/src/components/shared.styles.ts, interface/src/components/swap/account-modal/account-list-item-button.tsx, interface/src/components/swap/account-modal/account-modal.tsx, interface/src/components/swap/from-section.tsx, interface/src/components/swap/header.tsx, interface/src/components/swap/network-selector.tsx, interface/src/components/swap/quote-info.tsx, interface/src/components/swap/search-with-network-selector.tsx, interface/src/components/swap/select-token-modal.tsx, interface/src/components/swap/settings/swap-settings-modal.tsx, interface/src/components/swap/swap-container.tsx, interface/src/components/swap/swap-skeleton/skeleton.tsx, interface/src/components/swap/swap-skeleton/swap-skeleton.tsx, interface/src/utils/reduce-address.ts, interface/src/views/swap.tsx, sites/mock/package-lock.json, sites/mock/src/constants/locale.ts
Updates for `Swap V2` to look good on `mobile` devices.
Resolves <https://github.com/brave/brave-browser/issues/27423>
https://user-images.githubusercontent.com/40611140/214457470-932ad1c6-3161-4a1f-93d3-df14e84653d0.mov
=> fix(swap): Mobile UI Changes

interface/package-lock.json, interface/package.json, interface/src/components/swap/privacy-modal.tsx, sites/mock/package-lock.json, sites/mock/src/constants/locale.ts
Fixes duplicate strings in `Swap V2`
Resolves <https://github.com/brave/brave-browser/issues/28332>
=> fix(swap): Duplicate Locale Strings

interface/src/hooks/useJupiter.ts, interface/src/hooks/useSwap.ts, interface/src/hooks/useZeroEx.ts
Resolves https://github.com/brave/brave-browser/issues/28063.
https://user-images.githubusercontent.com/3684187/217821167-cfce64e2-cc64-455a-977b-1e4598b19ce1.mov
=> feat: add reset method to provider hooks

interface/package-lock.json, interface/package.json, interface/src/components/shared.styles.ts, interface/src/components/swap/header.tsx, interface/src/components/swap/swap-skeleton/swap-skeleton.tsx, sites/mock/package-lock.json
Updates the `Swap` header to match what we have in Wallet Core
Resolves <https://github.com/brave/brave-browser/issues/28722>
* `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
* `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
https://user-images.githubusercontent.com/40611140/221678950-036277fc-bf28-4198-b5cb-2079e8b04b5f.mov
=> fix(swap): Update Swap Header to Match Core

interface/src/hooks/useJupiter.ts, interface/src/hooks/useSwap.ts, interface/src/views/swap.tsx
This PR allows users to modify the "To Amount" field in Solana swaps. This field was previously disabled due to v1 API limitations.
https://github.com/brave/swap/assets/3684187/f7021020-7d3a-4369-a7bb-453f441a766d
=> feat: support ExactOut swap mode in Jupiter swaps
